#!/bin/bash

# Manual count from PDF Budget for Import-page17.pdf
# Counting each transaction line (not daily totals, not headers)

echo "JUNE 2024 TRANSACTION COUNT FROM PDF"
echo "===================================="
echo ""
echo "Saturday, June 1: 5 transactions"
echo "Sunday, June 2: 2 transactions"
echo "Monday, June 3: 3 transactions"
echo "Tuesday, June 4: 7 transactions"
echo "Wednesday, June 5: 1 transaction"
echo "Thursday, June 6: 0 transactions (blank day)"
echo "Friday, June 7: 1 transaction"
echo "Saturday, June 8: 8 transactions"
echo "Sunday, June 9: 2 transactions"
echo "Monday, June 10: 1 transaction"
echo "Tuesday, June 11: 3 transactions"
echo "Wednesday, June 12: 1 transaction"
echo "Thursday, June 13: 2 transactions"
echo "Friday, June 14: 1 transaction"
echo "Saturday, June 15: 8 transactions"
echo "Sunday, June 16: 5 transactions"
echo "Monday, June 17: 2 transactions (Mike D + Planet Fitness)"
echo "Tuesday, June 18: 0 transactions (blank day)"
echo "Wednesday, June 19: 2 transactions"
echo "Thursday, June 20: 4 transactions"
echo "Friday, June 21: 3 transactions"
echo "Saturday, June 22: 2 transactions"
echo "Sunday, June 23: 7 transactions"
echo "Monday, June 24: 5 transactions"
echo "Tuesday, June 25: 1 transaction"
echo "Wednesday, June 26: 1 transaction"
echo "Thursday, June 27: 4 transactions"
echo "Friday, June 28: 4 transactions"
echo "Saturday, June 29: 2 transactions"
echo "Sunday, June 30: 4 transactions"
echo ""
echo "TOTAL EXPENSE TRACKER: 90 transactions"
echo "GROSS INCOME: 6 transactions"
echo "SAVINGS: 1 transaction"
echo ""
echo "GRAND TOTAL: 97 transactions"
echo ""
echo "NOTE: Planet Fitness appears in PDF but has NO SUBTOTAL value"
echo "      It's listed but not counted in Daily Total"
