name: "Simple CI/CD Test"

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check deployment
        id: check
        run: |
          echo "should_deploy=true" >> $GITHUB_OUTPUT
          echo "Deployment check passed"

  deploy:
    runs-on: ubuntu-latest
    needs: preflight
    if: ${{ needs.preflight.outputs.should_deploy == 'true' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run build
        run: npm run build
